"""بيانات السيدر — بازارات ومنتجات مصرية"""

BAZAARS = [
    {"id":"bazaar_1","nameAr":"بازار خان الخليلي","nameEn":"Khan El Khalili Bazaar","descriptionAr":"أعرق سوق في القاهرة، تأسس في القرن الرابع عشر. يشتهر بالمجوهرات والتحف الفرعونية والعطور الشرقية.","address":"شارع الموسكي، الحسين، القاهرة","governorate":"القاهرة","latitude":30.0477,"longitude":31.2625,"rating":4.8,"reviewCount":2340,"workingHours":"10:00 ص - 12:00 م","isOpen":True,"phone":"02-25909800","imageUrl":"https://images.unsplash.com/photo-1553913861-c0a802e63f49?w=800"},
    {"id":"bazaar_2","nameAr":"سوق الأقصر السياحي","nameEn":"Luxor Tourist Souk","descriptionAr":"سوق سياحي بجانب معبد الأقصر، متخصص في التماثيل الفرعونية والمنحوتات الحجرية والبردي.","address":"كورنيش النيل، الأقصر","governorate":"الأقصر","latitude":25.6995,"longitude":32.6421,"rating":4.5,"reviewCount":890,"workingHours":"9:00 ص - 11:00 م","isOpen":True,"phone":"095-2372015","imageUrl":"https://images.unsplash.com/photo-1568322503122-d3e54e29e113?w=800"},
    {"id":"bazaar_3","nameAr":"بازار أسوان النوبي","nameEn":"Aswan Nubian Bazaar","descriptionAr":"سوق نوبي أصيل في جزيرة إلفنتين، متخصص في الحرف النوبية اليدوية والمنسوجات الملونة.","address":"جزيرة إلفنتين، أسوان","governorate":"أسوان","latitude":24.0889,"longitude":32.8998,"rating":4.7,"reviewCount":567,"workingHours":"8:00 ص - 10:00 م","isOpen":True,"phone":"097-2313456","imageUrl":"https://images.unsplash.com/photo-1590059390043-7567e4cacb09?w=800"},
    {"id":"bazaar_4","nameAr":"معرض الجيزة للتراث","nameEn":"Giza Heritage Gallery","descriptionAr":"معرض فاخر قرب أهرامات الجيزة، يقدم تماثيل عالية الجودة ولوحات بردي أصلية ومنحوتات حجرية.","address":"شارع الأهرام، الجيزة","governorate":"الجيزة","latitude":29.9773,"longitude":31.1325,"rating":4.6,"reviewCount":1230,"workingHours":"9:00 ص - 10:00 م","isOpen":True,"phone":"02-33837777","imageUrl":"https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800"},
    {"id":"bazaar_5","nameAr":"معرض الفسطاط للحرف","nameEn":"Fustat Crafts Gallery","descriptionAr":"مركز حرف يدوية في مصر القديمة، متخصص في النحاسيات المطعمة والخزف الإسلامي والفخار اليدوي.","address":"مجمع الفسطاط، مصر القديمة","governorate":"القاهرة","latitude":30.0065,"longitude":31.2313,"rating":4.4,"reviewCount":445,"workingHours":"10:00 ص - 8:00 م","isOpen":True,"phone":"02-23648722","imageUrl":"https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800"},
    {"id":"bazaar_6","nameAr":"بازار شرم الشيخ","nameEn":"Sharm El Sheikh Bazaar","descriptionAr":"بازار سياحي في خليج نعمة، يجمع بين الهدايا التذكارية والإكسسوارات البحرية والمنتجات المصرية.","address":"خليج نعمة، شرم الشيخ","governorate":"جنوب سيناء","latitude":27.9158,"longitude":34.3300,"rating":4.3,"reviewCount":678,"workingHours":"11:00 ص - 1:00 ص","isOpen":True,"phone":"069-3601234","imageUrl":"https://images.unsplash.com/photo-1548013146-72479768bada?w=800"},
    {"id":"bazaar_7","nameAr":"سوق الإسكندرية التراثي","nameEn":"Alexandria Heritage Souk","descriptionAr":"سوق عريق بالقرب من المكتبة، متخصص في التحف اليونانية-الرومانية والمنتجات البحرية التراثية.","address":"شارع فؤاد، وسط البلد، الإسكندرية","governorate":"الإسكندرية","latitude":31.2001,"longitude":29.9187,"rating":4.5,"reviewCount":560,"workingHours":"10:00 ص - 11:00 م","isOpen":True,"phone":"03-4861234","imageUrl":"https://images.unsplash.com/photo-1562679299-79cb889dbb1e?w=800"},
    {"id":"bazaar_8","nameAr":"بازار سيوة الأمازيغي","nameEn":"Siwa Amazigh Bazaar","descriptionAr":"بازار تراثي في واحة سيوة، متخصص في المشغولات الفضية الأمازيغية والمنسوجات والزيوت الطبيعية.","address":"شالي القديمة، واحة سيوة","governorate":"مطروح","latitude":29.2032,"longitude":25.5195,"rating":4.9,"reviewCount":234,"workingHours":"9:00 ص - 9:00 م","isOpen":True,"phone":"046-4601122","imageUrl":"https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800"},
]

PRODUCTS = [
    # === تماثيل فرعونية ===
    {"id":"product_1","nameAr":"تمثال توت عنخ آمون الذهبي","nameEn":"Golden Tutankhamun Statue","descriptionAr":"نسخة طبق الأصل من القناع الذهبي للملك توت عنخ آمون، مصنوع من الراتنج المطلي بالذهب عيار 18. تفاصيل دقيقة تشمل غطاء الرأس الملكي (النمس) وثعبان الكوبرا. قطعة فاخرة للديكور أو الهدايا.","descriptionEn":"Gold-plated replica of King Tutankhamun's death mask, made from 18K gold-plated resin with exquisite details.","category":"تماثيل","material":"راتنج مطلي بالذهب","dimensions":"25 × 18 × 30 سم","weight":"1.8 كجم","price":1500,"oldPrice":1800,"rating":4.9,"reviewCount":312,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_1","bazaarName":"بازار خان الخليلي","imageUrl":"https://images.unsplash.com/photo-1608326389673-56e60d213720?w=800","galleryImages":["https://images.unsplash.com/photo-1608326389673-56e60d213720?w=800","https://images.unsplash.com/photo-1562813733-b31f71025d54?w=800"],"sizes":["صغير 15سم","وسط 25سم","كبير 40سم"]},
    {"id":"product_2","nameAr":"تمثال نفرتيتي الكلاسيكي","nameEn":"Classic Nefertiti Bust","descriptionAr":"نسخة من تمثال نصفي للملكة نفرتيتي المعروض في متحف برلين. منحوت يدوياً من الحجر الجيري المصري بنفس الألوان الأصلية. رمز الجمال المصري القديم.","descriptionEn":"Handcrafted limestone replica of the iconic Queen Nefertiti bust with original colors.","category":"تماثيل","material":"حجر جيري منحوت يدوياً","dimensions":"20 × 15 × 35 سم","weight":"2.5 كجم","price":1200,"oldPrice":None,"rating":4.8,"reviewCount":245,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_2","bazaarName":"سوق الأقصر السياحي","imageUrl":"https://images.unsplash.com/photo-1562813733-b31f71025d54?w=800","galleryImages":["https://images.unsplash.com/photo-1562813733-b31f71025d54?w=800"],"sizes":["وسط 25سم","كبير 45سم"]},
    {"id":"product_3","nameAr":"تمثال أبو الهول المصغّر","nameEn":"Miniature Sphinx Statue","descriptionAr":"نموذج مصغر لأبو الهول بتفاصيل محفورة يدوياً. مصنوع من حجر الباسلت الأسود الطبيعي. قاعدة مزخرفة بهيروغليفية.","descriptionEn":"Miniature Sphinx model carved from natural black basalt with hieroglyphic base.","category":"تماثيل","material":"حجر باسلت طبيعي","dimensions":"20 × 10 × 12 سم","weight":"1.2 كجم","price":450,"oldPrice":550,"rating":4.6,"reviewCount":189,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_4","bazaarName":"معرض الجيزة للتراث","imageUrl":"https://images.unsplash.com/photo-1568322503122-d3e54e29e113?w=800","galleryImages":["https://images.unsplash.com/photo-1568322503122-d3e54e29e113?w=800"],"sizes":["صغير 12سم","وسط 20سم","كبير 35سم"]},
    {"id":"product_4","nameAr":"تمثال أنوبيس حارس المقابر","nameEn":"Anubis Guardian Statue","descriptionAr":"تمثال إله الموت أنوبيس برأس ابن آوى، مصنوع من الراتنج الأسود مع تفاصيل ذهبية. يمثل حارس المقابر في الميثولوجيا المصرية.","descriptionEn":"Black resin Anubis statue with gold details, representing the guardian of tombs.","category":"تماثيل","material":"راتنج أسود وذهبي","dimensions":"15 × 10 × 30 سم","weight":"900 جرام","price":680,"oldPrice":None,"rating":4.7,"reviewCount":156,"isFeatured":False,"isNew":True,"bazaarId":"bazaar_2","bazaarName":"سوق الأقصر السياحي","imageUrl":"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800","galleryImages":["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800"],"sizes":["وسط 20سم","كبير 35سم"]},
    {"id":"product_5","nameAr":"تمثال حورس الصقر الملكي","nameEn":"Royal Horus Falcon Statue","descriptionAr":"تمثال الإله حورس على شكل صقر يرتدي التاج المزدوج لمصر العليا والسفلى. منحوت من الرخام المصري بتفاصيل مذهّبة يدوياً.","descriptionEn":"Marble Horus falcon statue wearing the double crown, with hand-gilded details.","category":"تماثيل","material":"رخام مصري مذهّب","dimensions":"18 × 12 × 28 سم","weight":"1.5 كجم","price":950,"oldPrice":1100,"rating":4.8,"reviewCount":198,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_1","bazaarName":"بازار خان الخليلي","imageUrl":"https://images.unsplash.com/photo-1565118531796-763e5082d113?w=800","galleryImages":["https://images.unsplash.com/photo-1565118531796-763e5082d113?w=800"],"sizes":["وسط 22سم","كبير 38سم"]},
    # === مجوهرات ===
    {"id":"product_6","nameAr":"عقد عين حورس الفضي","nameEn":"Silver Eye of Horus Necklace","descriptionAr":"عقد من الفضة الإسترليني عيار 925 بتعليقة عين حورس المرصعة بالفيروز الطبيعي. رمز الحماية والشفاء عند الفراعنة. سلسلة 50 سم.","descriptionEn":"Sterling silver 925 Eye of Horus pendant with natural turquoise inlay.","category":"مجوهرات","material":"فضة إسترليني 925 وفيروز","dimensions":"سلسلة 50 سم، التعليقة 3 سم","weight":"25 جرام","price":380,"oldPrice":None,"rating":4.7,"reviewCount":267,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_1","bazaarName":"بازار خان الخليلي","imageUrl":"https://images.unsplash.com/photo-1515562141589-67f0d569b6b3?w=800","galleryImages":["https://images.unsplash.com/photo-1515562141589-67f0d569b6b3?w=800"],"sizes":["40 سم","45 سم","50 سم"]},
    {"id":"product_7","nameAr":"أسورة فرعونية ذهبية","nameEn":"Pharaonic Gold Bracelet","descriptionAr":"أسورة عريضة مستوحاة من مجوهرات الملكة كليوباترا. مصنوعة من النحاس المطلي بالذهب مع نقوش هيروغليفية محفورة يدوياً.","descriptionEn":"Wide bracelet inspired by Cleopatra's jewelry, gold-plated brass with hieroglyphic engravings.","category":"مجوهرات","material":"نحاس مطلي بالذهب","dimensions":"قطر 7 سم، عرض 4 سم","weight":"85 جرام","price":520,"oldPrice":620,"rating":4.6,"reviewCount":178,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_1","bazaarName":"بازار خان الخليلي","imageUrl":"https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800","galleryImages":["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800"],"sizes":["S","M","L"]},
    {"id":"product_8","nameAr":"عقد فيروز سيناوي","nameEn":"Sinai Turquoise Necklace","descriptionAr":"عقد من الفيروز السيناوي الأصلي مع خرز فضة. قطعة فريدة من التراث البدوي السيناوي، كل حجر منتقى يدوياً.","descriptionEn":"Authentic Sinai turquoise necklace with silver beads, each stone hand-selected.","category":"مجوهرات","material":"فيروز طبيعي وفضة","dimensions":"45 سم طول","weight":"80 جرام","price":650,"oldPrice":None,"rating":4.5,"reviewCount":89,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_1","bazaarName":"بازار خان الخليلي","imageUrl":"https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=800","galleryImages":["https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=800"],"sizes":["40 سم","45 سم","50 سم"]},
    {"id":"product_9","nameAr":"خاتم الجعران المقدس","nameEn":"Sacred Scarab Ring","descriptionAr":"خاتم فضة بتصميم الجعران المقدس، رمز الحظ والبعث عند المصريين القدماء. الجعران من اللازورد الطبيعي.","descriptionEn":"Silver scarab ring with natural lapis lazuli, symbol of luck and rebirth.","category":"مجوهرات","material":"فضة 925 ولازورد طبيعي","dimensions":"قطر الجعران 1.5 سم","weight":"12 جرام","price":290,"oldPrice":None,"rating":4.8,"reviewCount":145,"isFeatured":False,"isNew":True,"bazaarId":"bazaar_8","bazaarName":"بازار سيوة الأمازيغي","imageUrl":"https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800","galleryImages":["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800"],"sizes":["مقاس 7","مقاس 8","مقاس 9","مقاس 10"]},
    # === بردي ===
    {"id":"product_10","nameAr":"لوحة بردي - كتاب الموتى","nameEn":"Papyrus - Book of the Dead","descriptionAr":"لوحة بردي مرسومة يدوياً تصور مشهد المحاكمة من كتاب الموتى الفرعوني (وزن القلب أمام ريشة ماعت). ألوان طبيعية من أكاسيد المعادن.","descriptionEn":"Hand-painted papyrus depicting the Judgment Scene from the Book of the Dead.","category":"بردي","material":"ورق بردي طبيعي وألوان معدنية","dimensions":"60 × 40 سم","weight":"100 جرام","price":350,"oldPrice":None,"rating":4.7,"reviewCount":223,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_4","bazaarName":"معرض الجيزة للتراث","imageUrl":"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800","galleryImages":["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800"],"sizes":["30×20 سم","60×40 سم","90×60 سم"]},
    {"id":"product_11","nameAr":"لوحة بردي - خريطة مصر القديمة","nameEn":"Papyrus - Ancient Egypt Map","descriptionAr":"خريطة مصر القديمة مرسومة على بردي طبيعي، تُظهر النيل والمعابد والأهرامات. مُحاطة بإطار هيروغليفي.","descriptionEn":"Ancient Egypt map painted on natural papyrus showing the Nile, temples and pyramids.","category":"بردي","material":"بردي طبيعي","dimensions":"50 × 35 سم","weight":"80 جرام","price":280,"oldPrice":320,"rating":4.5,"reviewCount":167,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_4","bazaarName":"معرض الجيزة للتراث","imageUrl":"https://images.unsplash.com/photo-1633164690057-e30e9b10f498?w=800","galleryImages":["https://images.unsplash.com/photo-1633164690057-e30e9b10f498?w=800"],"sizes":["30×20 سم","50×35 سم"]},
    # === أواني وخزف ===
    {"id":"product_12","nameAr":"طقم شاي نحاسي مطعم","nameEn":"Inlaid Brass Tea Set","descriptionAr":"طقم شاي نحاسي مكون من إبريق و6 أكواب، مطعم بالفضة بنقوش إسلامية هندسية. صناعة يدوية من حي الفسطاط.","descriptionEn":"Brass tea set with teapot and 6 cups, silver-inlaid geometric Islamic patterns.","category":"نحاسيات","material":"نحاس مطعم بالفضة","dimensions":"30 × 30 × 25 سم","weight":"2.8 كجم","price":1100,"oldPrice":None,"rating":4.8,"reviewCount":134,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_5","bazaarName":"معرض الفسطاط للحرف","imageUrl":"https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=800","galleryImages":["https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=800"],"sizes":["6 أشخاص","12 شخص"]},
    {"id":"product_13","nameAr":"إناء كانوبي فرعوني","nameEn":"Pharaonic Canopic Jar","descriptionAr":"نسخة من الأواني الكانوبية الأربعة (أبناء حورس)، كانت تُستخدم لحفظ أعضاء المومياء. مصنوع من السيراميك المطلي يدوياً.","descriptionEn":"Replica canopic jar from the Four Sons of Horus, hand-painted ceramic.","category":"خزف","material":"سيراميك مطلي يدوياً","dimensions":"12 × 12 × 25 سم","weight":"1 كجم","price":380,"oldPrice":None,"rating":4.6,"reviewCount":98,"isFeatured":False,"isNew":True,"bazaarId":"bazaar_2","bazaarName":"سوق الأقصر السياحي","imageUrl":"https://images.unsplash.com/photo-1590059390043-7567e4cacb09?w=800","galleryImages":["https://images.unsplash.com/photo-1590059390043-7567e4cacb09?w=800"],"sizes":["صغير 15سم","وسط 25سم"]},
    {"id":"product_14","nameAr":"طبق خزف إسلامي مزخرف","nameEn":"Decorated Islamic Ceramic Plate","descriptionAr":"طبق خزف مزخرف بنقوش عربية وإسلامية هندسية. مصنوع من الفخار المصري ومطلي بطلاء لامع يدوياً. للعرض والزينة.","descriptionEn":"Ceramic plate with Arabic and Islamic geometric patterns, hand-glazed.","category":"خزف","material":"فخار مصري مطلي","dimensions":"قطر 30 سم","weight":"800 جرام","price":250,"oldPrice":None,"rating":4.4,"reviewCount":112,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_5","bazaarName":"معرض الفسطاط للحرف","imageUrl":"https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800","galleryImages":["https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800"],"sizes":["قطر 20سم","قطر 30سم","قطر 40سم"]},
    # === ملابس وأقمشة ===
    {"id":"product_15","nameAr":"جلابية مصرية مطرزة","nameEn":"Embroidered Egyptian Galabiya","descriptionAr":"جلابية قطنية مصرية أصيلة بتطريز يدوي فرعوني على الصدر والأكمام. قماش قطن مصري 100% مريح وخفيف.","descriptionEn":"Authentic Egyptian cotton galabiya with hand-embroidered pharaonic patterns.","category":"ملابس","material":"قطن مصري 100%","dimensions":"طول 140 سم","weight":"350 جرام","price":320,"oldPrice":380,"rating":4.5,"reviewCount":201,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_3","bazaarName":"بازار أسوان النوبي","imageUrl":"https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800","galleryImages":["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800"],"sizes":["S","M","L","XL","XXL"]},
    {"id":"product_16","nameAr":"شال حريري بنقوش فرعونية","nameEn":"Pharaonic Silk Scarf","descriptionAr":"شال حريري فاخر مطبوع عليه رسومات فرعونية (عين حورس والجعران). حرير طبيعي 100% مع حواف مشغولة يدوياً.","descriptionEn":"Luxury silk scarf printed with Eye of Horus and Scarab designs, 100% natural silk.","category":"ملابس","material":"حرير طبيعي 100%","dimensions":"180 × 70 سم","weight":"120 جرام","price":450,"oldPrice":None,"rating":4.7,"reviewCount":134,"isFeatured":True,"isNew":True,"bazaarId":"bazaar_7","bazaarName":"سوق الإسكندرية التراثي","imageUrl":"https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800","galleryImages":["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800"],"sizes":["90×70 سم","180×70 سم"]},
    {"id":"product_17","nameAr":"طاقية نوبية ملونة","nameEn":"Colorful Nubian Cap","descriptionAr":"طاقية يدوية من التراث النوبي بألوان زاهية (أحمر، أصفر، أخضر). محاكة من القطن الطبيعي بأنامل نوبية.","descriptionEn":"Handmade Nubian cap with vibrant traditional colors, natural cotton.","category":"ملابس","material":"قطن طبيعي","dimensions":"مقاس واحد","weight":"60 جرام","price":85,"oldPrice":None,"rating":4.3,"reviewCount":167,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_3","bazaarName":"بازار أسوان النوبي","imageUrl":"https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800","galleryImages":["https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800"],"sizes":["مقاس واحد"]},
    # === كتب ===
    {"id":"product_18","nameAr":"موسوعة الفراعنة المصورة","nameEn":"Illustrated Pharaohs Encyclopedia","descriptionAr":"موسوعة شاملة عن الحضارة الفرعونية بالعربية والإنجليزية. 320 صفحة بصور ملونة عالية الجودة تشمل كل السلالات الفرعونية.","descriptionEn":"Comprehensive bilingual encyclopedia of ancient Egyptian civilization, 320 full-color pages.","category":"كتب","material":"ورق مصقول فاخر","dimensions":"30 × 22 × 3 سم","weight":"1.2 كجم","price":280,"oldPrice":350,"rating":4.9,"reviewCount":89,"isFeatured":False,"isNew":True,"bazaarId":"bazaar_4","bazaarName":"معرض الجيزة للتراث","imageUrl":"https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=800","galleryImages":["https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=800"],"sizes":["غلاف عادي","غلاف فاخر"]},
    {"id":"product_19","nameAr":"كتاب أسرار الهيروغليفية","nameEn":"Secrets of Hieroglyphics","descriptionAr":"دليل تعليمي لفك رموز الهيروغليفية المصرية القديمة. يشمل قاموس مصور و200 رمز مشروح مع تمارين تفاعلية.","descriptionEn":"Educational guide to decoding ancient Egyptian hieroglyphics with 200 illustrated symbols.","category":"كتب","material":"ورق مصقول","dimensions":"25 × 18 × 2 سم","weight":"500 جرام","price":150,"oldPrice":None,"rating":4.6,"reviewCount":234,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_7","bazaarName":"سوق الإسكندرية التراثي","imageUrl":"https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800","galleryImages":["https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800"],"sizes":["غلاف عادي"]},
    # === تحف وديكور ===
    {"id":"product_20","nameAr":"قناع فرعوني ذهبي للحائط","nameEn":"Golden Pharaonic Wall Mask","descriptionAr":"قناع ملكي فرعوني للتعليق على الحائط. نسخة من قناع توت عنخ آمون بحجم نصف الحقيقي. مصنوع من الفايبرجلاس المطلي.","descriptionEn":"Half-size wall-mount replica of Tutankhamun's mask, fiberglass with gold finish.","category":"تحف","material":"فايبرجلاس مطلي بالذهب","dimensions":"30 × 25 × 10 سم","weight":"1.5 كجم","price":750,"oldPrice":900,"rating":4.8,"reviewCount":89,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_4","bazaarName":"معرض الجيزة للتراث","imageUrl":"https://images.unsplash.com/photo-1560461396-ec0ef7bb29dd?w=800","galleryImages":["https://images.unsplash.com/photo-1560461396-ec0ef7bb29dd?w=800"],"sizes":["نصف حقيقي","ربع حقيقي"]},
    {"id":"product_21","nameAr":"صندوق مجوهرات فرعوني خشبي","nameEn":"Pharaonic Wooden Jewelry Box","descriptionAr":"صندوق مجوهرات من خشب الجوز المصري محفور عليه مشاهد فرعونية. بطانة مخملية من الداخل مع مرآة. صناعة يدوية 100%.","descriptionEn":"Handcrafted walnut jewelry box with carved pharaonic scenes and velvet lining.","category":"تحف","material":"خشب جوز مصري","dimensions":"25 × 18 × 12 سم","weight":"900 جرام","price":420,"oldPrice":None,"rating":4.5,"reviewCount":156,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_5","bazaarName":"معرض الفسطاط للحرف","imageUrl":"https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800","galleryImages":["https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800"],"sizes":["صغير","كبير"]},
    {"id":"product_22","nameAr":"فانوس نحاسي منقوش","nameEn":"Engraved Brass Lantern","descriptionAr":"فانوس نحاسي تقليدي بنقوش إسلامية هندسية مخرّمة. يُعطي إضاءة ساحرة بنمط ظلال جميل. مثالي للديكور الشرقي.","descriptionEn":"Traditional brass lantern with pierced Islamic geometric patterns, creates beautiful shadow patterns.","category":"تحف","material":"نحاس أصفر","dimensions":"15 × 15 × 35 سم","weight":"1.3 كجم","price":380,"oldPrice":None,"rating":4.6,"reviewCount":198,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_5","bazaarName":"معرض الفسطاط للحرف","imageUrl":"https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800","galleryImages":["https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800"],"sizes":["صغير 20سم","وسط 35سم","كبير 50سم"]},
    # === زيوت وعطور ===
    {"id":"product_23","nameAr":"مجموعة زيوت عطرية مصرية","nameEn":"Egyptian Essential Oils Collection","descriptionAr":"مجموعة من 6 زيوت عطرية مصرية أصلية: لوتس مصري، ياسمين سيناء، مسك عربي، عنبر، ورد بلدي، صندل. في علبة خشبية فاخرة.","descriptionEn":"Collection of 6 authentic Egyptian essential oils in a luxury wooden box.","category":"عطور","material":"زيوت عطرية طبيعية","dimensions":"20 × 15 × 5 سم","weight":"400 جرام","price":550,"oldPrice":650,"rating":4.9,"reviewCount":312,"isFeatured":True,"isNew":False,"bazaarId":"bazaar_1","bazaarName":"بازار خان الخليلي","imageUrl":"https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=800","galleryImages":["https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=800"],"sizes":["6 زجاجات 10مل","6 زجاجات 30مل"]},
    {"id":"product_24","nameAr":"بخور اللبان الصعيدي","nameEn":"Upper Egypt Frankincense","descriptionAr":"بخور لبان ذكر أصلي من صعيد مصر. رائحة روحانية دافئة تملأ المكان. يأتي في علبة خشبية مع مبخرة نحاسية صغيرة.","descriptionEn":"Authentic Upper Egypt frankincense with a small brass incense burner.","category":"عطور","material":"لبان ذكر طبيعي","dimensions":"10 × 10 × 8 سم","weight":"200 جرام","price":120,"oldPrice":None,"rating":4.4,"reviewCount":178,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_2","bazaarName":"سوق الأقصر السياحي","imageUrl":"https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800","galleryImages":["https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800"],"sizes":["100 جرام","250 جرام"]},
    # === إكسسوارات ===
    {"id":"product_25","nameAr":"ميدالية مفاتيح فرعونية","nameEn":"Pharaonic Keychain Set","descriptionAr":"طقم 3 ميداليات مفاتيح معدنية: توت عنخ آمون، عنخ (مفتاح الحياة)، وعين حورس. مطلية بالذهب والفضة مع تفاصيل دقيقة.","descriptionEn":"Set of 3 pharaonic keychains: Tutankhamun, Ankh, and Eye of Horus.","category":"إكسسوارات","material":"معدن مطلي","dimensions":"5 × 3 سم لكل ميدالية","weight":"90 جرام","price":95,"oldPrice":120,"rating":4.3,"reviewCount":445,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_6","bazaarName":"بازار شرم الشيخ","imageUrl":"https://images.unsplash.com/photo-1622396636133-8be631a73428?w=800","galleryImages":["https://images.unsplash.com/photo-1622396636133-8be631a73428?w=800"],"sizes":["طقم 3 قطع"]},
    {"id":"product_26","nameAr":"حقيبة قطنية برسوم فرعونية","nameEn":"Pharaonic Cotton Tote Bag","descriptionAr":"حقيبة قماشية من القطن المصري مطبوع عليها رسومات فرعونية ملونة. عملية للتسوق والسفر، صديقة للبيئة.","descriptionEn":"Egyptian cotton tote bag with colorful pharaonic print, eco-friendly.","category":"إكسسوارات","material":"قطن مصري","dimensions":"40 × 35 سم","weight":"150 جرام","price":75,"oldPrice":None,"rating":4.2,"reviewCount":289,"isFeatured":False,"isNew":True,"bazaarId":"bazaar_6","bazaarName":"بازار شرم الشيخ","imageUrl":"https://images.unsplash.com/photo-1597633425046-08f5110420b5?w=800","galleryImages":["https://images.unsplash.com/photo-1597633425046-08f5110420b5?w=800"],"sizes":["مقاس واحد"]},
    # === منسوجات نوبية ===
    {"id":"product_27","nameAr":"سجادة نوبية يدوية","nameEn":"Handwoven Nubian Rug","descriptionAr":"سجادة منسوجة يدوياً بألوان وأنماط نوبية تقليدية. من أيادي حرفيات نوبيات في أسوان. كل قطعة فريدة.","descriptionEn":"Handwoven Nubian rug with traditional patterns, made by Nubian artisans in Aswan.","category":"منسوجات","material":"قطن وصوف طبيعي","dimensions":"120 × 80 سم","weight":"1.5 كجم","price":680,"oldPrice":None,"rating":4.8,"reviewCount":78,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_3","bazaarName":"بازار أسوان النوبي","imageUrl":"https://images.unsplash.com/photo-1600166898405-da9535204843?w=800","galleryImages":["https://images.unsplash.com/photo-1600166898405-da9535204843?w=800"],"sizes":["80×60 سم","120×80 سم","180×120 سم"]},
    {"id":"product_28","nameAr":"مفرش طاولة قبطي مطرز","nameEn":"Embroidered Coptic Table Runner","descriptionAr":"مفرش طاولة من الكتان المصري مطرز يدوياً بصلبان قبطية ونقوش تراثية. من ورش أسيوط الشهيرة بالتطريز.","descriptionEn":"Hand-embroidered Egyptian linen table runner with Coptic cross patterns from Asyut.","category":"منسوجات","material":"كتان مصري","dimensions":"150 × 40 سم","weight":"300 جرام","price":220,"oldPrice":None,"rating":4.5,"reviewCount":67,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_3","bazaarName":"بازار أسوان النوبي","imageUrl":"https://images.unsplash.com/photo-1578898886225-c7c894047899?w=800","galleryImages":["https://images.unsplash.com/photo-1578898886225-c7c894047899?w=800"],"sizes":["100×40 سم","150×40 سم"]},
    # === فضة سيوة ===
    {"id":"product_29","nameAr":"طقم فضة أمازيغي سيوي","nameEn":"Siwan Amazigh Silver Set","descriptionAr":"طقم من 3 قطع فضة سيوية: خلخال، أسورة، وعقد. تصميمات أمازيغية تقليدية بأحجار فيروزية. صناعة يدوية من حرفيي سيوة.","descriptionEn":"3-piece Siwan silver set: anklet, bracelet, and necklace with Amazigh designs.","category":"مجوهرات","material":"فضة سيوية وفيروز","dimensions":"متنوعة","weight":"180 جرام","price":1200,"oldPrice":1400,"rating":4.9,"reviewCount":56,"isFeatured":True,"isNew":True,"bazaarId":"bazaar_8","bazaarName":"بازار سيوة الأمازيغي","imageUrl":"https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800","galleryImages":["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800"],"sizes":["S","M","L"]},
    # === هدايا بحرية ===
    {"id":"product_30","nameAr":"مجسم مركب فرعوني خشبي","nameEn":"Wooden Pharaonic Boat Model","descriptionAr":"نموذج مصغر لمركب الشمس الفرعوني (مركب خوفو). مصنوع يدوياً من خشب الأرز مع تفاصيل دقيقة للمجاديف والأشرعة.","descriptionEn":"Handcrafted cedar wood model of the Solar Boat of Khufu with detailed oars and sails.","category":"تحف","material":"خشب أرز طبيعي","dimensions":"45 × 10 × 20 سم","weight":"600 جرام","price":520,"oldPrice":None,"rating":4.7,"reviewCount":134,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_4","bazaarName":"معرض الجيزة للتراث","imageUrl":"https://images.unsplash.com/photo-1569974498991-d3c12a504f95?w=800","galleryImages":["https://images.unsplash.com/photo-1569974498991-d3c12a504f95?w=800"],"sizes":["30 سم","45 سم","60 سم"]},
    {"id":"product_31","nameAr":"لوحة موزاييك فرعونية","nameEn":"Pharaonic Mosaic Art","descriptionAr":"لوحة موزاييك من الأحجار الطبيعية الملونة تصور مشهد صيد فرعوني. كل قطعة حجر مقصوصة ومركبة يدوياً.","descriptionEn":"Natural stone mosaic depicting a pharaonic hunting scene, hand-cut and assembled.","category":"تحف","material":"أحجار طبيعية ملونة","dimensions":"40 × 30 سم","weight":"2 كجم","price":890,"oldPrice":None,"rating":4.8,"reviewCount":45,"isFeatured":False,"isNew":True,"bazaarId":"bazaar_7","bazaarName":"سوق الإسكندرية التراثي","imageUrl":"https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=800","galleryImages":["https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=800"],"sizes":["30×20 سم","40×30 سم"]},
    {"id":"product_32","nameAr":"زيت أرجان مصري عضوي","nameEn":"Organic Egyptian Argan Oil","descriptionAr":"زيت أرجان مصري عضوي 100% معصور على البارد. للعناية بالبشرة والشعر. في زجاجة داكنة فاخرة مع قطارة.","descriptionEn":"100% organic cold-pressed Egyptian argan oil for skin and hair care.","category":"عطور","material":"زيت أرجان عضوي","dimensions":"5 × 5 × 12 سم","weight":"120 جرام","price":180,"oldPrice":220,"rating":4.7,"reviewCount":267,"isFeatured":False,"isNew":False,"bazaarId":"bazaar_8","bazaarName":"بازار سيوة الأمازيغي","imageUrl":"https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800","galleryImages":["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800"],"sizes":["30 مل","50 مل","100 مل"]},
]
